//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DeTai.EF_QLSCXeMay
{

    public partial class KhachHangs : XPLiteObject
    {
        string fMaKH;
        [Key]
        [Size(128)]
        public string MaKH
        {
            get { return fMaKH; }
            set { SetPropertyValue<string>("MaKH", ref fMaKH, value); }
        }
        string fTenKH;
        [Size(SizeAttribute.Unlimited)]
        public string TenKH
        {
            get { return fTenKH; }
            set { SetPropertyValue<string>("TenKH", ref fTenKH, value); }
        }
        string fSoDienThoai;
        [Size(SizeAttribute.Unlimited)]
        public string SoDienThoai
        {
            get { return fSoDienThoai; }
            set { SetPropertyValue<string>("SoDienThoai", ref fSoDienThoai, value); }
        }
        string fDiaChi;
        [Size(SizeAttribute.Unlimited)]
        public string DiaChi
        {
            get { return fDiaChi; }
            set { SetPropertyValue<string>("DiaChi", ref fDiaChi, value); }
        }
        bool fdeleted;
        public bool deleted
        {
            get { return fdeleted; }
            set { SetPropertyValue<bool>("deleted", ref fdeleted, value); }
        }
        [Association(@"Xe_KhachReferencesKhachHangs", typeof(Xe_Khach))]
        public XPCollection<Xe_Khach> Xe_Khachs { get { return GetCollection<Xe_Khach>("Xe_Khachs"); } }
    }

}
