//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DeTai.EF_QLSCXeMay
{

    public partial class MucDoThanhThao : XPLiteObject
    {
        string fid;
        [Key]
        [Size(128)]
        public string id
        {
            get { return fid; }
            set { SetPropertyValue<string>("id", ref fid, value); }
        }
        CongViecs fMaCV;
        [Size(128)]
        [Association(@"MucDoThanhThaoReferencesCongViecs")]
        public CongViecs MaCV
        {
            get { return fMaCV; }
            set { SetPropertyValue<CongViecs>("MaCV", ref fMaCV, value); }
        }
        int fMucDo;
        public int MucDo
        {
            get { return fMucDo; }
            set { SetPropertyValue<int>("MucDo", ref fMucDo, value); }
        }
        bool fdeleted;
        public bool deleted
        {
            get { return fdeleted; }
            set { SetPropertyValue<bool>("deleted", ref fdeleted, value); }
        }
        NhanVien fMaNV;
        [Size(128)]
        [Association(@"MucDoThanhThaoReferencesNhanVien")]
        public NhanVien MaNV
        {
            get { return fMaNV; }
            set { SetPropertyValue<NhanVien>("MaNV", ref fMaNV, value); }
        }
    }

}
