//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DeTai.EF_QLSCXeMay
{

    public partial class NhanVien : XPLiteObject
    {
        string fMaNV;
        [Key]
        [Size(128)]
        public string MaNV
        {
            get { return fMaNV; }
            set { SetPropertyValue<string>("MaNV", ref fMaNV, value); }
        }
        string fTenNV;
        [Size(SizeAttribute.Unlimited)]
        public string TenNV
        {
            get { return fTenNV; }
            set { SetPropertyValue<string>("TenNV", ref fTenNV, value); }
        }
        string fSDT;
        [Size(SizeAttribute.Unlimited)]
        public string SDT
        {
            get { return fSDT; }
            set { SetPropertyValue<string>("SDT", ref fSDT, value); }
        }
        string fDiaChi;
        [Size(SizeAttribute.Unlimited)]
        public string DiaChi
        {
            get { return fDiaChi; }
            set { SetPropertyValue<string>("DiaChi", ref fDiaChi, value); }
        }
        bool fdeleted;
        public bool deleted
        {
            get { return fdeleted; }
            set { SetPropertyValue<bool>("deleted", ref fdeleted, value); }
        }
        DateTime fNamSinh;
        public DateTime NamSinh
        {
            get { return fNamSinh; }
            set { SetPropertyValue<DateTime>("NamSinh", ref fNamSinh, value); }
        }
        LoaiNV fLoaiNhanVien;
        [Size(10)]
        [Association(@"NhanVienReferencesLoaiNV")]
        public LoaiNV LoaiNhanVien
        {
            get { return fLoaiNhanVien; }
            set { SetPropertyValue<LoaiNV>("LoaiNhanVien", ref fLoaiNhanVien, value); }
        }
        double fLuong;
        public double Luong
        {
            get { return fLuong; }
            set { SetPropertyValue<double>("Luong", ref fLuong, value); }
        }
        bool fGioiTinh;
        public bool GioiTinh
        {
            get { return fGioiTinh; }
            set { SetPropertyValue<bool>("GioiTinh", ref fGioiTinh, value); }
        }
        [Association(@"MucDoThanhThaoReferencesNhanVien", typeof(MucDoThanhThao))]
        public XPCollection<MucDoThanhThao> MucDoThanhThaos { get { return GetCollection<MucDoThanhThao>("MucDoThanhThaos"); } }
        [Association(@"NhomThoesReferencesNhanVien", typeof(NhomThoes))]
        public XPCollection<NhomThoes> NhomThoesCollection { get { return GetCollection<NhomThoes>("NhomThoesCollection"); } }
        [Association(@"Tho_NhomReferencesNhanVien", typeof(Tho_Nhom))]
        public XPCollection<Tho_Nhom> Tho_Nhoms { get { return GetCollection<Tho_Nhom>("Tho_Nhoms"); } }
    }

}
