//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DeTai.EF_QLSCXeMay
{

    public partial class NhaSanXuat : XPLiteObject
    {
        string fMaNSX;
        [Key]
        [Size(10)]
        public string MaNSX
        {
            get { return fMaNSX; }
            set { SetPropertyValue<string>("MaNSX", ref fMaNSX, value); }
        }
        string fTenNSX;
        [Size(50)]
        public string TenNSX
        {
            get { return fTenNSX; }
            set { SetPropertyValue<string>("TenNSX", ref fTenNSX, value); }
        }
        string fDiaChi;
        [Size(50)]
        public string DiaChi
        {
            get { return fDiaChi; }
            set { SetPropertyValue<string>("DiaChi", ref fDiaChi, value); }
        }
        string fSoDienThoai;
        [Size(15)]
        public string SoDienThoai
        {
            get { return fSoDienThoai; }
            set { SetPropertyValue<string>("SoDienThoai", ref fSoDienThoai, value); }
        }
        bool fdeleted;
        public bool deleted
        {
            get { return fdeleted; }
            set { SetPropertyValue<bool>("deleted", ref fdeleted, value); }
        }
        [Association(@"ThietBiReferencesNhaSanXuat", typeof(ThietBi))]
        public XPCollection<ThietBi> ThietBis { get { return GetCollection<ThietBi>("ThietBis"); } }
    }

}
