//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DeTai.EF_QLSCXeMay
{

    public partial class SuaChuas : XPLiteObject
    {
        string fMaSC;
        [Key]
        [Size(128)]
        public string MaSC
        {
            get { return fMaSC; }
            set { SetPropertyValue<string>("MaSC", ref fMaSC, value); }
        }
        Xe_Khach fIDXe_Khach;
        [Size(128)]
        [Association(@"SuaChuasReferencesXe_Khach")]
        public Xe_Khach IDXe_Khach
        {
            get { return fIDXe_Khach; }
            set { SetPropertyValue<Xe_Khach>("IDXe_Khach", ref fIDXe_Khach, value); }
        }
        DateTime fNgaySC;
        public DateTime NgaySC
        {
            get { return fNgaySC; }
            set { SetPropertyValue<DateTime>("NgaySC", ref fNgaySC, value); }
        }
        bool fTinhtrang;
        public bool Tinhtrang
        {
            get { return fTinhtrang; }
            set { SetPropertyValue<bool>("Tinhtrang", ref fTinhtrang, value); }
        }
        bool fdeleted;
        public bool deleted
        {
            get { return fdeleted; }
            set { SetPropertyValue<bool>("deleted", ref fdeleted, value); }
        }
        string fGhiChu;
        [Size(500)]
        public string GhiChu
        {
            get { return fGhiChu; }
            set { SetPropertyValue<string>("GhiChu", ref fGhiChu, value); }
        }
        double fDaThu;
        public double DaThu
        {
            get { return fDaThu; }
            set { SetPropertyValue<double>("DaThu", ref fDaThu, value); }
        }
        [Association(@"ChiTietSuaChuaReferencesSuaChuas", typeof(ChiTietSuaChua))]
        public XPCollection<ChiTietSuaChua> ChiTietSuaChuas { get { return GetCollection<ChiTietSuaChua>("ChiTietSuaChuas"); } }
        [Association(@"PhieuThusReferencesSuaChuas", typeof(PhieuThus))]
        public XPCollection<PhieuThus> PhieuThusCollection { get { return GetCollection<PhieuThus>("PhieuThusCollection"); } }
    }

}
