//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DeTai.EF_QLSCXeMay
{

    public partial class TaiKhoans : XPLiteObject
    {
        string fUserName;
        [Key]
        [Size(128)]
        public string UserName
        {
            get { return fUserName; }
            set { SetPropertyValue<string>("UserName", ref fUserName, value); }
        }
        string fPassword;
        [Size(SizeAttribute.Unlimited)]
        public string Password
        {
            get { return fPassword; }
            set { SetPropertyValue<string>("Password", ref fPassword, value); }
        }
        QuyenTruyCaps fMaQuyen;
        [Size(128)]
        [Association(@"TaiKhoansReferencesQuyenTruyCaps")]
        public QuyenTruyCaps MaQuyen
        {
            get { return fMaQuyen; }
            set { SetPropertyValue<QuyenTruyCaps>("MaQuyen", ref fMaQuyen, value); }
        }
        bool fTrangThai;
        public bool TrangThai
        {
            get { return fTrangThai; }
            set { SetPropertyValue<bool>("TrangThai", ref fTrangThai, value); }
        }
        bool fdeleted;
        public bool deleted
        {
            get { return fdeleted; }
            set { SetPropertyValue<bool>("deleted", ref fdeleted, value); }
        }
        [Association(@"PhieuThusReferencesTaiKhoans", typeof(PhieuThus))]
        public XPCollection<PhieuThus> PhieuThusCollection { get { return GetCollection<PhieuThus>("PhieuThusCollection"); } }
    }

}
