//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DeTai.EF_QLSCXeMay
{

    public partial class Xe_Khach : XPLiteObject
    {
        string fID;
        [Key]
        [Size(128)]
        public string ID
        {
            get { return fID; }
            set { SetPropertyValue<string>("ID", ref fID, value); }
        }
        KhachHangs fMaKH;
        [Size(128)]
        [Association(@"Xe_KhachReferencesKhachHangs")]
        public KhachHangs MaKH
        {
            get { return fMaKH; }
            set { SetPropertyValue<KhachHangs>("MaKH", ref fMaKH, value); }
        }
        Xes fMaXe;
        [Size(128)]
        [Association(@"Xe_KhachReferencesXes")]
        public Xes MaXe
        {
            get { return fMaXe; }
            set { SetPropertyValue<Xes>("MaXe", ref fMaXe, value); }
        }
        bool fdeleted;
        public bool deleted
        {
            get { return fdeleted; }
            set { SetPropertyValue<bool>("deleted", ref fdeleted, value); }
        }
        [Association(@"SuaChuasReferencesXe_Khach", typeof(SuaChuas))]
        public XPCollection<SuaChuas> SuaChuasCollection { get { return GetCollection<SuaChuas>("SuaChuasCollection"); } }
    }

}
