using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using DevExpress.XtraGrid.Views.Grid;

namespace DeTai
{
    public partial class FormAddThietBiSuaChua : DevExpress.XtraEditors.XtraForm
    {
        public ThietBi thietbi;
        public FormAddThietBiSuaChua()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            searchLookUpEdit1.Properties.DataSource = new DeTai.SCXMdbDataContext().ThietBis;
        }

        private void btnOk_Click(object sender, EventArgs e)
        {
            try
            {
                GridView view = searchLookUpEdit1.Properties.View;
                int rowHandle = view.FocusedRowHandle;
                thietbi = view.GetRow(rowHandle) as ThietBi;
                this.DialogResult = DialogResult.OK;
            }
            catch (Exception ex)
            { }
        }
    }
}