//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DeTai.EF_QLSCXeMay
{

    public partial class ChiTietSuaChua : XPLiteObject
    {
        string fMaCTSC;
        [Key]
        [Size(128)]
        public string MaCTSC
        {
            get { return fMaCTSC; }
            set { SetPropertyValue<string>("MaCTSC", ref fMaCTSC, value); }
        }
        SuaChuas fMaSC;
        [Size(128)]
        [Association(@"ChiTietSuaChuaReferencesSuaChuas")]
        public SuaChuas MaSC
        {
            get { return fMaSC; }
            set { SetPropertyValue<SuaChuas>("MaSC", ref fMaSC, value); }
        }
        double fTienCong;
        public double TienCong
        {
            get { return fTienCong; }
            set { SetPropertyValue<double>("TienCong", ref fTienCong, value); }
        }
        bool fdeleted;
        public bool deleted
        {
            get { return fdeleted; }
            set { SetPropertyValue<bool>("deleted", ref fdeleted, value); }
        }
        [Association(@"CongViecSuaChuaReferencesChiTietSuaChua", typeof(CongViecSuaChua))]
        public XPCollection<CongViecSuaChua> CongViecSuaChuas { get { return GetCollection<CongViecSuaChua>("CongViecSuaChuas"); } }
        [Association(@"ThietBiSuaChuaReferencesChiTietSuaChua", typeof(ThietBiSuaChua))]
        public XPCollection<ThietBiSuaChua> ThietBiSuaChuas { get { return GetCollection<ThietBiSuaChua>("ThietBiSuaChuas"); } }
    }

}
