//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DeTai.EF_QLSCXeMay
{

    public partial class LoaiNV : XPLiteObject
    {
        string fMaLoaiNV;
        [Key]
        [Size(10)]
        public string MaLoaiNV
        {
            get { return fMaLoaiNV; }
            set { SetPropertyValue<string>("MaLoaiNV", ref fMaLoaiNV, value); }
        }
        string fTenLoaiNV;
        [Size(50)]
        public string TenLoaiNV
        {
            get { return fTenLoaiNV; }
            set { SetPropertyValue<string>("TenLoaiNV", ref fTenLoaiNV, value); }
        }
        bool fdeleted;
        public bool deleted
        {
            get { return fdeleted; }
            set { SetPropertyValue<bool>("deleted", ref fdeleted, value); }
        }
        string fMoTa;
        [Size(200)]
        public string MoTa
        {
            get { return fMoTa; }
            set { SetPropertyValue<string>("MoTa", ref fMoTa, value); }
        }
        [Association(@"NhanVienReferencesLoaiNV", typeof(NhanVien))]
        public XPCollection<NhanVien> NhanViens { get { return GetCollection<NhanVien>("NhanViens"); } }
    }

}
