//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DeTai.EF_QLSCXeMay
{

    public partial class LoaiXes : XPLiteObject
    {
        string fMaLXe;
        [Key]
        [Size(128)]
        public string MaLXe
        {
            get { return fMaLXe; }
            set { SetPropertyValue<string>("MaLXe", ref fMaLXe, value); }
        }
        string fTenLXe;
        [Size(SizeAttribute.Unlimited)]
        public string TenLXe
        {
            get { return fTenLXe; }
            set { SetPropertyValue<string>("TenLXe", ref fTenLXe, value); }
        }
        bool fdeleted;
        public bool deleted
        {
            get { return fdeleted; }
            set { SetPropertyValue<bool>("deleted", ref fdeleted, value); }
        }
        string fMoTa;
        [Size(200)]
        public string MoTa
        {
            get { return fMoTa; }
            set { SetPropertyValue<string>("MoTa", ref fMoTa, value); }
        }
        [Association(@"XesReferencesLoaiXes", typeof(Xes))]
        public XPCollection<Xes> XesCollection { get { return GetCollection<Xes>("XesCollection"); } }
    }

}
