//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DeTai.EF_QLSCXeMay
{

    public partial class LoaiThietBis : XPLiteObject
    {
        string fMaLoaiTB;
        [Key]
        [Size(10)]
        public string MaLoaiTB
        {
            get { return fMaLoaiTB; }
            set { SetPropertyValue<string>("MaLoaiTB", ref fMaLoaiTB, value); }
        }
        string fTenLoaiTB;
        [Size(50)]
        public string TenLoaiTB
        {
            get { return fTenLoaiTB; }
            set { SetPropertyValue<string>("TenLoaiTB", ref fTenLoaiTB, value); }
        }
        bool fdeleted;
        public bool deleted
        {
            get { return fdeleted; }
            set { SetPropertyValue<bool>("deleted", ref fdeleted, value); }
        }
        string fMoTa;
        [Size(200)]
        public string MoTa
        {
            get { return fMoTa; }
            set { SetPropertyValue<string>("MoTa", ref fMoTa, value); }
        }
        [Association(@"ThietBiReferencesLoaiThietBis", typeof(ThietBi))]
        public XPCollection<ThietBi> ThietBis { get { return GetCollection<ThietBi>("ThietBis"); } }
    }

}
