//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DeTai.EF_QLSCXeMay
{

    public partial class NhomThoes : XPLiteObject
    {
        string fMaNhom;
        [Key]
        [Size(128)]
        public string MaNhom
        {
            get { return fMaNhom; }
            set { SetPropertyValue<string>("MaNhom", ref fMaNhom, value); }
        }
        string fTenNhom;
        [Size(SizeAttribute.Unlimited)]
        public string TenNhom
        {
            get { return fTenNhom; }
            set { SetPropertyValue<string>("TenNhom", ref fTenNhom, value); }
        }
        NhanVien fTruongNhom;
        [Size(128)]
        [Association(@"NhomThoesReferencesNhanVien")]
        public NhanVien TruongNhom
        {
            get { return fTruongNhom; }
            set { SetPropertyValue<NhanVien>("TruongNhom", ref fTruongNhom, value); }
        }
        bool fdeleted;
        public bool deleted
        {
            get { return fdeleted; }
            set { SetPropertyValue<bool>("deleted", ref fdeleted, value); }
        }
        [Association(@"Tho_NhomReferencesNhomThoes", typeof(Tho_Nhom))]
        public XPCollection<Tho_Nhom> Tho_Nhoms { get { return GetCollection<Tho_Nhom>("Tho_Nhoms"); } }
    }

}
