//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DeTai.EF_QLSCXeMay
{

    public partial class QuyenTruyCaps : XPLiteObject
    {
        string fMaQuyen;
        [Key]
        [Size(128)]
        public string MaQuyen
        {
            get { return fMaQuyen; }
            set { SetPropertyValue<string>("MaQuyen", ref fMaQuyen, value); }
        }
        string fTenQuyen;
        [Size(SizeAttribute.Unlimited)]
        public string TenQuyen
        {
            get { return fTenQuyen; }
            set { SetPropertyValue<string>("TenQuyen", ref fTenQuyen, value); }
        }
        string fGhiChu;
        [Size(SizeAttribute.Unlimited)]
        public string GhiChu
        {
            get { return fGhiChu; }
            set { SetPropertyValue<string>("GhiChu", ref fGhiChu, value); }
        }
        bool fdeleted;
        public bool deleted
        {
            get { return fdeleted; }
            set { SetPropertyValue<bool>("deleted", ref fdeleted, value); }
        }
        [Association(@"TaiKhoansReferencesQuyenTruyCaps", typeof(TaiKhoans))]
        public XPCollection<TaiKhoans> TaiKhoansCollection { get { return GetCollection<TaiKhoans>("TaiKhoansCollection"); } }
    }

}
