//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DeTai.EF_QLSCXeMay
{

    public partial class ThietBi : XPLiteObject
    {
        string fMaThietBi;
        [Key]
        [Size(128)]
        public string MaThietBi
        {
            get { return fMaThietBi; }
            set { SetPropertyValue<string>("MaThietBi", ref fMaThietBi, value); }
        }
        string fTenThietBi;
        [Size(50)]
        public string TenThietBi
        {
            get { return fTenThietBi; }
            set { SetPropertyValue<string>("TenThietBi", ref fTenThietBi, value); }
        }
        double fDonGia;
        public double DonGia
        {
            get { return fDonGia; }
            set { SetPropertyValue<double>("DonGia", ref fDonGia, value); }
        }
        string fDonVi;
        [Size(50)]
        public string DonVi
        {
            get { return fDonVi; }
            set { SetPropertyValue<string>("DonVi", ref fDonVi, value); }
        }
        int fSoLuong;
        public int SoLuong
        {
            get { return fSoLuong; }
            set { SetPropertyValue<int>("SoLuong", ref fSoLuong, value); }
        }
        LoaiThietBis fMaLoaiTB;
        [Size(10)]
        [Association(@"ThietBiReferencesLoaiThietBis")]
        public LoaiThietBis MaLoaiTB
        {
            get { return fMaLoaiTB; }
            set { SetPropertyValue<LoaiThietBis>("MaLoaiTB", ref fMaLoaiTB, value); }
        }
        NhaSanXuat fNhaSanXuat;
        [Size(10)]
        [Association(@"ThietBiReferencesNhaSanXuat")]
        public NhaSanXuat NhaSanXuat
        {
            get { return fNhaSanXuat; }
            set { SetPropertyValue<NhaSanXuat>("NhaSanXuat", ref fNhaSanXuat, value); }
        }
        bool fdeleted;
        public bool deleted
        {
            get { return fdeleted; }
            set { SetPropertyValue<bool>("deleted", ref fdeleted, value); }
        }
        string fQuyCach;
        [Size(50)]
        public string QuyCach
        {
            get { return fQuyCach; }
            set { SetPropertyValue<string>("QuyCach", ref fQuyCach, value); }
        }
        int fBaoHanh;
        public int BaoHanh
        {
            get { return fBaoHanh; }
            set { SetPropertyValue<int>("BaoHanh", ref fBaoHanh, value); }
        }
        double fGiaNhap;
        public double GiaNhap
        {
            get { return fGiaNhap; }
            set { SetPropertyValue<double>("GiaNhap", ref fGiaNhap, value); }
        }
        int fmin;
        public int min
        {
            get { return fmin; }
            set { SetPropertyValue<int>("min", ref fmin, value); }
        }
        [Association(@"ThietBiSuaChuaReferencesThietBi", typeof(ThietBiSuaChua))]
        public XPCollection<ThietBiSuaChua> ThietBiSuaChuas { get { return GetCollection<ThietBiSuaChua>("ThietBiSuaChuas"); } }
    }

}
