//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DeTai.EF_QLSCXeMay
{

    public partial class Xes : XPLiteObject
    {
        string fMaXe;
        [Key]
        [Size(128)]
        public string MaXe
        {
            get { return fMaXe; }
            set { SetPropertyValue<string>("MaXe", ref fMaXe, value); }
        }
        LoaiXes fMaLXe;
        [Size(128)]
        [Association(@"XesReferencesLoaiXes")]
        public LoaiXes MaLXe
        {
            get { return fMaLXe; }
            set { SetPropertyValue<LoaiXes>("MaLXe", ref fMaLXe, value); }
        }
        string fMauXe;
        [Size(SizeAttribute.Unlimited)]
        public string MauXe
        {
            get { return fMauXe; }
            set { SetPropertyValue<string>("MauXe", ref fMauXe, value); }
        }
        bool fdeleted;
        public bool deleted
        {
            get { return fdeleted; }
            set { SetPropertyValue<bool>("deleted", ref fdeleted, value); }
        }
        [Association(@"Xe_KhachReferencesXes", typeof(Xe_Khach))]
        public XPCollection<Xe_Khach> Xe_Khachs { get { return GetCollection<Xe_Khach>("Xe_Khachs"); } }
    }

}
